
name: continuous_integration
on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: '143.110.167.9'
          username: 'webmaster'
          privateKey: ${{ secrets.SSHKEY}}
          command:
            cd lcpt_twitter_bot/ && python3 run.py




