
name: continuous_integration
on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo '$SSH_KEY' > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: 'webmaster'
          SSH_HOST: '143.110.167.9'
          SSH_KEY: ${{ secrets.SSHKEY }}

      - name: testing
        run: |
          ls -al
          whoami
          pwd
          touch ~/hello.txt
          touch /tmp/hello.txt

