
name: deploy
on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Executing remote command
      #uses: appleboy/ssh-action@master
      uses: garygrossgarten/github-action-ssh@release
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
          #passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.SSHKEY}}
        command: ls -al
          #whoami
          #pwd
          #ls -la
          #touch /tmp/hello_.txt
