
name: continuous_integration
on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: 'webmaster'
          SSH_HOST: '143.110.167.9'
          SSH_KEY: ${{ secrets.SSHKEY }}

      - name: testing
        run: |
          tail -n1 ~/.ssh/staging.key
          ssh staging whoami
          ssh staging "ls -al"
          ssh staging pwd
          ssh staging "touch ./hello1.txt"
          ssh staging "touch ~/hello2.txt"
          ssh staging "touch /tmp/hello.txt"

