
name: continuous_integration
on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: '143.110.167.9'
          username: 'webmaster'
          privateKey: ${{ secrets.SSHKEY}}
          command:
            cd lcpt_twitter_bot/ && python3 run.py
          env:
            RAINDROP_CLIENT_ID: ${{ secrets.RAINDROP_CLIENT_ID }}
            RAINDROP_CLIENT_SECRET: ${{ secrets.RAINDROP_CLIENT_SECRET }}
            RAINDROP_TOKEN: ${{ secrets.RAINDROP_TOKEN }}
            TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
            TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
            TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}




